### ISSUE TITLE
TypeError: vSpot(...).client is not a function

### ISSUE THREAD

**Issue by miminashi** [realglobe-Inc/v-daemon#1]
https://github.com/realglobe-Inc/v-daemon/blob/master/README.md#usage のStep3のコードを試そうとしたのですが、`TypeError: vSpot(...).client is not a function`というエラーになりました。
これはどうしたらよいでしょう？

```node
> 'use strict'
'use strict'
> vSpot = require('v-spot')
{ [Function: bound create]
  server: [Function: server],
  client: [Function: client],
  VSpot: 
   { [Function: VSpot]
     Server: [Function: VSpotServer],
     Client: [Function: VSpotClient] },
  VSpotServer: [Function: VSpotServer],
  VSpotClient: [Function: VSpotClient],
  create: { [Function: create] server: [Function: server], client: [Function: client] } }
> spot = vSpot().client()
TypeError: vSpot(...).client is not a function
    at repl:1:16
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
    at REPLServer.Interface._onLine (readline.js:282:10)
    at REPLServer.Interface._line (readline.js:631:8)
```

**Comment by miminashi** [comment]
`spot = vSpot.client()` としたらVSpotClientオブジェクトはかえってきました。

ここから先がよくわかりません。
（Promiseとawaitをあまりよくわかってないです）

```
> await client.use('jp.realglobe.daisan.humidifier-02')
await client.use('jp.realglobe.daisan.humidifier-02')
      ^^^^^^

SyntaxError: Unexpected identifier
```

**Comment by okunishinishi** [comment]
@miminashi `await`を使うことができるのは`async`に囲まれた中という制約がありまして。

```javascript
;(async () => {
    const humidifier02 = await client.use('jp.realglobe.daisan.humidifier-02')
})() // asyncな関数を定義して即時実行
```

みたいにやるとうまくいくと思います。
